# Generated by Django 4.2.3 on 2023-07-29 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_condition_id_pledge_pledge_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='pledge',
        ),
        migrations.AddField(
            model_name='condition',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pledge',
            name='condition',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.condition'),
        ),
    ]
