# Generated by Django 4.2.3 on 2023-07-29 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_condition_pledge_condition_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='condition',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='projects.condition'),
        ),
    ]
