# Generated by Django 4.0.7 on 2023-08-05 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_pledge_condition_condition_pledge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='pledge',
        ),
        migrations.AddField(
            model_name='pledge',
            name='condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pledge', to='projects.condition'),
        ),
    ]
