# Generated by Django 4.0.7 on 2023-08-05 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_condition_pledge_pledge_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='condition',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='projects.condition'),
        ),
    ]
